-- ─────────────────────────────────────────────────────────────────────────────
-- Booklyt business identity: unique 6-digit business code + app opt-out flag.
-- The code powers universal links (https://booklyt.net/app/business/<code>),
-- deep links (booklyt://business/<code>) and QR codes.
-- Generated by a BEFORE INSERT trigger so it can never be skipped, regardless
-- of where the insert originates (onboarding page inserts client-side).
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.businesses
  add column if not exists business_code text unique,
  add column if not exists app_enabled   boolean not null default true;

-- Random 6-digit code, retried on collision (bounded, fails loudly).
create or replace function public.generate_business_code()
returns text
language plpgsql
as $$
declare
  candidate text;
  attempts  int := 0;
begin
  loop
    attempts := attempts + 1;
    if attempts > 50 then
      raise exception 'generate_business_code: could not find a free code after 50 attempts';
    end if;
    candidate := lpad(floor(random() * 1000000)::int::text, 6, '0');
    exit when not exists (
      select 1 from public.businesses where business_code = candidate
    );
  end loop;
  return candidate;
end;
$$;

create or replace function public.set_business_code()
returns trigger
language plpgsql
as $$
begin
  if new.business_code is null then
    new.business_code := public.generate_business_code();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_business_code on public.businesses;
create trigger trg_set_business_code
  before insert on public.businesses
  for each row
  execute function public.set_business_code();

-- Backfill existing businesses (row by row so each gets a fresh collision check)
do $$
declare
  b record;
begin
  for b in select id from public.businesses where business_code is null loop
    update public.businesses
      set business_code = public.generate_business_code()
      where id = b.id;
  end loop;
end;
$$;
