import type { TemplatePreset } from '@/types/builder'

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    name: 'Editorial',
    nameAr: 'تحريري',
    slug: 'luxury-barber',
    description: 'A split photographic cover, oversized serif type and a numbered service menu.',
    descriptionAr: 'غلاف مصوّر مقسوم، خط كبير أنيق، وقائمة خدمات مرقّمة.',
    preview: '',
    brand: {
      primaryColor: '#c9a227',
      accentColor: '#1a1a2e',
      backgroundColor: '#0d0d14',
      surfaceColor: '#1a1a2e',
      textColor: '#f5f5f7',
      mutedColor: '#aaa9af',
      font: 'Cormorant Garamond',
      radius: '8px',
      buttonStyle: 'sharp',
      cardStyle: 'bordered',
    },
    layout: {
      templateName: 'luxury-barber',
      websiteStyle: 'editorial',
      sections: [
        { id: 'hero', type: 'hero', visible: true, variant: 'split', order: 0 },
        { id: 'services', type: 'services', visible: true, variant: 'minimal', order: 1 },
        { id: 'staff', type: 'staff', visible: true, variant: 'default', order: 2 },
        { id: 'booking', type: 'booking', visible: true, variant: 'default', order: 3 },
        { id: 'testimonials', type: 'testimonials', visible: true, variant: 'minimal', order: 4 },
        { id: 'contact', type: 'contact', visible: true, variant: 'default', order: 5 },
        { id: 'about', type: 'about', visible: true, variant: 'default', order: 6 },
        { id: 'gallery', type: 'gallery', visible: false, variant: 'default', order: 7 },
      ],
      spacingStyle: 'comfortable',
      pageStyle: 'dark',
    },
    content: {
      heroTitle: 'Look Sharp.\nFeel Your Best.',
      heroSubtitle: 'Haircuts, beard care and time in the chair. Choose your service and find a time that suits you.',
      heroCtaText: 'Book Your Cut',
    },
  },
  {
    name: 'Atelier',
    nameAr: 'أتيليه',
    slug: 'soft-salon',
    description: 'A centred masthead, panoramic cover image and a visual service collection.',
    descriptionAr: 'عنوان في الوسط، صورة غلاف عريضة، ومجموعة خدمات مصوّرة.',
    preview: '',
    brand: {
      primaryColor: '#b76e79',
      accentColor: '#f9e4e8',
      backgroundColor: '#fff9f8',
      surfaceColor: '#ffffff',
      textColor: '#2d1b1e',
      mutedColor: '#796168',
      font: 'DM Serif Display',
      radius: '16px',
      buttonStyle: 'pill',
      cardStyle: 'elevated',
    },
    layout: {
      templateName: 'soft-salon',
      websiteStyle: 'atelier',
      sections: [
        { id: 'hero', type: 'hero', visible: true, variant: 'centered', order: 0 },
        { id: 'services', type: 'services', visible: true, variant: 'default', order: 1 },
        { id: 'gallery', type: 'gallery', visible: true, variant: 'default', order: 2 },
        { id: 'staff', type: 'staff', visible: true, variant: 'centered', order: 3 },
        { id: 'booking', type: 'booking', visible: true, variant: 'default', order: 4 },
        { id: 'testimonials', type: 'testimonials', visible: true, variant: 'default', order: 5 },
        { id: 'contact', type: 'contact', visible: true, variant: 'default', order: 6 },
        { id: 'about', type: 'about', visible: true, variant: 'centered', order: 7 },
      ],
      spacingStyle: 'spacious',
      pageStyle: 'light',
    },
    content: {
      heroTitle: 'Your Hair,\nYour Confidence.',
      heroSubtitle: 'From a fresh cut to your next colour. Explore our services and plan your visit.',
      heroCtaText: 'Book Appointment',
    },
  },
  {
    name: 'Modern Practice',
    nameAr: 'عيادة حديثة',
    slug: 'minimal-clinic',
    description: 'A compact introduction, clear service rows and an appointment overview.',
    descriptionAr: 'مقدمة مختصرة، صفوف خدمات واضحة، ونظرة سريعة على المواعيد.',
    preview: '',
    brand: {
      primaryColor: '#2563eb',
      accentColor: '#eff6ff',
      backgroundColor: '#ffffff',
      surfaceColor: '#f8fafc',
      textColor: '#0f172a',
      mutedColor: '#64748b',
      font: 'Inter',
      radius: '12px',
      buttonStyle: 'rounded',
      cardStyle: 'flat',
    },
    layout: {
      templateName: 'minimal-clinic',
      websiteStyle: 'practice',
      sections: [
        { id: 'hero', type: 'hero', visible: true, variant: 'split', order: 0 },
        { id: 'services', type: 'services', visible: true, variant: 'minimal', order: 1 },
        { id: 'staff', type: 'staff', visible: true, variant: 'minimal', order: 2 },
        { id: 'booking', type: 'booking', visible: true, variant: 'centered', order: 3 },
        { id: 'contact', type: 'contact', visible: true, variant: 'split', order: 4 },
        { id: 'testimonials', type: 'testimonials', visible: false, variant: 'default', order: 5 },
        { id: 'about', type: 'about', visible: true, variant: 'default', order: 6 },
        { id: 'gallery', type: 'gallery', visible: false, variant: 'default', order: 7 },
      ],
      spacingStyle: 'comfortable',
      pageStyle: 'light',
    },
    content: {
      heroTitle: 'Care that fits\nyour schedule.',
      heroSubtitle: 'Explore our services, meet the team and choose an appointment time.',
      heroCtaText: 'Book Consultation',
    },
  },
  {
    name: 'Performance',
    nameAr: 'أداء',
    slug: 'bold-fitness',
    description: 'An immersive full-width cover, bold type and a structured service grid.',
    descriptionAr: 'غلاف بعرض الشاشة، خط عريض، وشبكة خدمات منظمة.',
    preview: '',
    brand: {
      primaryColor: '#22c55e',
      accentColor: '#052e16',
      backgroundColor: '#030712',
      surfaceColor: '#111827',
      textColor: '#f9fafb',
      mutedColor: 'rgba(249,250,251,0.5)',
      font: 'Outfit',
      radius: '6px',
      buttonStyle: 'sharp',
      cardStyle: 'bordered',
    },
    layout: {
      templateName: 'bold-fitness',
      websiteStyle: 'performance',
      sections: [
        { id: 'hero', type: 'hero', visible: true, variant: 'bold', order: 0 },
        { id: 'services', type: 'services', visible: true, variant: 'bold', order: 1 },
        { id: 'about', type: 'about', visible: true, variant: 'default', order: 2 },
        { id: 'staff', type: 'staff', visible: true, variant: 'default', order: 3 },
        { id: 'booking', type: 'booking', visible: true, variant: 'default', order: 4 },
        { id: 'testimonials', type: 'testimonials', visible: true, variant: 'bold', order: 5 },
        { id: 'contact', type: 'contact', visible: true, variant: 'default', order: 6 },
        { id: 'gallery', type: 'gallery', visible: false, variant: 'default', order: 7 },
      ],
      spacingStyle: 'compact',
      pageStyle: 'dark',
    },
    content: {
      heroTitle: 'Make time\nto move.',
      heroSubtitle: 'Find your next training session and reserve a time that works for you.',
      heroCtaText: 'Book Session',
    },
  },
  {
    name: 'Quiet Luxury',
    nameAr: 'فخامة هادئة',
    slug: 'elegant-spa',
    description: 'Portrait photography, generous spacing and individual treatment cards.',
    descriptionAr: 'صور عمودية، مساحات واسعة، وبطاقة لكل جلسة.',
    preview: '',
    brand: {
      primaryColor: '#8b6f47',
      accentColor: '#fdf6ee',
      backgroundColor: '#fdf9f4',
      surfaceColor: '#ffffff',
      textColor: '#2c1810',
      mutedColor: '#806653',
      font: 'Playfair Display',
      radius: '20px',
      buttonStyle: 'pill',
      cardStyle: 'elevated',
    },
    layout: {
      templateName: 'elegant-spa',
      websiteStyle: 'retreat',
      sections: [
        { id: 'hero', type: 'hero', visible: true, variant: 'centered', order: 0 },
        { id: 'services', type: 'services', visible: true, variant: 'centered', order: 1 },
        { id: 'gallery', type: 'gallery', visible: true, variant: 'default', order: 2 },
        { id: 'about', type: 'about', visible: true, variant: 'centered', order: 3 },
        { id: 'staff', type: 'staff', visible: true, variant: 'centered', order: 4 },
        { id: 'testimonials', type: 'testimonials', visible: true, variant: 'centered', order: 5 },
        { id: 'booking', type: 'booking', visible: true, variant: 'default', order: 6 },
        { id: 'contact', type: 'contact', visible: true, variant: 'centered', order: 7 },
      ],
      spacingStyle: 'spacious',
      pageStyle: 'light',
    },
    content: {
      heroTitle: 'A little time\nfor yourself.',
      heroSubtitle: 'Explore our treatments and make room in your day to slow down.',
      heroCtaText: 'Book a Treatment',
    },
  },
]

export const DEFAULT_TEMPLATE = TEMPLATE_PRESETS[0]

export function getTemplate(slug: string): TemplatePreset {
  return TEMPLATE_PRESETS.find(t => t.slug === slug) ?? DEFAULT_TEMPLATE
}
