// Generate the PWA icon set from the SVG sources in public/icons/.
//   node scripts/make-icons.mjs
//
// The original project rendered these from photographic brand logos. This
// build draws them from flat SVGs instead, so the repository carries no
// branding and the icons can be regenerated by anyone who clones it.
// For each logo it writes <name>-192, <name>-512 (plain squares), a padded
// <name>-maskable (so Android adaptive masks don't crop the artwork) and an
// <name>-apple.png (180) for iOS "Add to Home Screen".
import sharp from "sharp";
import { existsSync } from "node:fs";

const BG = { r: 0x1c, g: 0x17, b: 0x12, alpha: 1 }; // dark, behind maskable padding

// source basename -> output prefix
const LOGOS = [
  { src: "logo.svg", out: "logo" },     // dashboard + workers kiosk
  { src: "driver.svg", out: "driver" }, // driver
  { src: "baker.svg", out: "baker" },   // production
];

async function square(src, size, out) {
  await sharp(src).resize(size, size, { fit: "cover", position: "centre" }).png().toFile(out);
  console.log("wrote", out);
}

async function maskable(src, size, out, pad = 0.14) {
  const inner = Math.round(size * (1 - pad * 2));
  const logo = await sharp(src).resize(inner, inner, { fit: "contain", background: BG }).toBuffer();
  await sharp({ create: { width: size, height: size, channels: 4, background: BG } })
    .composite([{ input: logo, gravity: "centre" }])
    .png()
    .toFile(out);
  console.log("wrote", out);
}

for (const { src, out } of LOGOS) {
  const path = `public/icons/${src}`;
  if (!existsSync(path)) {
    console.error(`Missing ${path} — skipping ${out}`);
    continue;
  }
  await square(path, 192, `public/icons/${out}-192.png`);
  await square(path, 512, `public/icons/${out}-512.png`);
  await square(path, 180, `public/icons/${out}-apple.png`);
  await maskable(path, 512, `public/icons/${out}-maskable.png`);
}
console.log("done");
